### PR TITLE
Code quality improvement

### PR DESCRIPTION
**Pull request by withshubh**
Hey @mherrmann, I am opening this PR to fix a few [interesting code quality issues](https://deepsource.io/gh/withshubh/selenium-python-helium/issues/) that were detected on static analysis of this repo. This analysis was performed with DeepSource, a code review automation tool that detects problems in contributions and helps developers automatically fix some of them.
 
### Changes

- Removed methods with unnecessary super delegation.
- Removed unused imports
- Removed unnecessary generator
- ~Used `hypot` method to calculate the hypotenuse~
- ~Added .deepsource.toml config~

### CODE REVIEW

**Comment by mherrmann** [comment]
Thanks. I understand you're promoting your tool. The changes look quite good, actually. But I don't want to have `.deepsource.toml` in my source tree. Also I can't merge your PR until you've signed the CLA. Finally, your use of `hypot` seems invalid.

**Comment by withshubh** [comment]
> Thanks. I understand you're promoting your tool. The changes look quite good, actually. But I don't want to have `.deepsource.toml` in my source tree. Also I can't merge your PR until you've signed the CLA. Finally, your use of `hypot` seems invalid.

Hi @mherrmann :wave: 

I signed the CLA right after submitting the PR but It is not updated here. Is there any other way to re-run the CLA check apart from clicking on clicking "recheck".

**Comment by mherrmann** [comment]
Maybe it doesn't work because @deepsourcebot would need to sign the CLA. Anyways, I do see that you've signed, which is good enough.

The other points remain though. `hypot` is used incorrectly and I don't want to have `.deepsource.toml` in my source tree.

**Comment by withshubh** [comment]
> Maybe it doesn't work because @deepsourcebot would need to sign the CLA. Anyways, I do see that you've signed, which is good enough.
> 
> The other points remain though. `hypot` is used incorrectly and I don't want to have `.deepsource.toml` in my source tree.

Updated the PR with the changes! :sparkles:

**Comment by mherrmann** [comment]
Thanks!

**Pull request merged**
