### PR TITLE
Add docs

### PR DESCRIPTION
**Pull request by IgnisDa**
Reference #38

### CODE REVIEW

**Review by mherrmann — COMMENTED** [review]
This already looks a lot better, thank you very much. Some very quick comments.

1. Please only add those lines to `.gitignore` that are really needed. I don't think it makes sense to have Django-related lines in there, for example, because this project will never use Django.

2. I feel like requirements-dev.txt now also contains transitive dependencies (autopep8, flake8, urllib3). Please use `-r requirements.txt` in `requirements-dev.txt` and remove the ones I just mentioned.

3. I took great care in `helium/__init__.py` to order the functions by relevance. The Sphinx documentation however displays them in alphabetical order. It would be amazing if you could make it so Sphinx's docs have the same order as helium/__init__.py, so readers can very quickly see the most important functions.

Thanks!

**Comment by IgnisDa** [comment]
1. The `.gitignore` I added earlier is the default one provided by github when starting python projects. I removed as many of them as I could (and should).
2. Removed `autopep8` and `flake8` from `requirements-dev.txt` but the last one remains since its a dependency of `selenium`.
3. I tried to do this, following [this](https://stackoverflow.com/a/37210251/11667450) but it doesn't work. Maybe open a new issue for it?

**Comment by IgnisDa** [comment]
Hello @mherrmann, it has been a week since our last interaction. Can I get an update if you are planning to merge the PR?

**Comment by IgnisDa** [comment]
Thank you very much. Next step is to host this documentation somewhere. I recommend `readthedocs` since it's the standard that python community uses to host documentation. But it's up to you to choose what you would like to use. Github pages is another one.

**Comment by mherrmann** [comment]
Thank _you_. I've set it up at ReadTheDocs now: https://selenium-python-helium.readthedocs.io/en/latest/. I'd like to make you a maintainer of ReadTheDocs. Is your username there also IgnisDa?

**Comment by IgnisDa** [comment]
Yes my username is IgnisDa there. I propose that we add a `installation.rst` which would get new users started. Additionally, we have to provide a relevant section on the README and then optionally cut down the README to something smaller. I can submit a PR for this.

**Comment by mherrmann** [comment]
Sounds good, thank you. I've added you as a maintainer on Readthedocs. I think we should also have the Cheatsheet there.

**Pull request merged**
