### PR TITLE
Add documentation 

### PR DESCRIPTION
**Pull request by IgnisDa**
Here's what I changed:
- Change default documentation folder from `doc/` to `docs/`. Update README accordingly.
- Change default package configuration file from `setup.py` to `pyproject.toml` as according to [pep517](https://www.python.org/dev/peps/pep-0517/) (under review)
- Add flake8 configuration to enable consistent code style among all contributors.

Reference: #38

### CODE REVIEW

**Comment by IgnisDa** [comment]
Regarding the move to `poetry`, I can add all relevant documentation including setting up the project locally in the root README.md

**Comment by IgnisDa** [comment]
1. Sure that is perfectly fine by me. But the project doesn't contain any `requirements.txt` or am I missing something here? 

2. Can you please tell me what formatted you use? The one I use (autopep8) doesn't allow me to use tabs for indentation. I can convert the spaces back to tabs, that's not an issue.

3. I will remove the `.flake8` assuming I can get the formatter you use to work.

4. I will incorporate my `.gitignore` with yours, not an issue again.

**Comment by mherrmann** [comment]
1. You're right; Sorry. I meant listing the requirements in `setup.py`.
2. I don't use any formatter. I just write my code by hand.
3. Thanks!
4. Also thanks :hugs:

**Comment by IgnisDa** [comment]
> 1. You're right; Sorry. I meant listing the requirements in `setup.py`.

Would it be okay to add a `requirements.txt`? This will hugely benefit future contributors when they are trying to set up the project locally for development.

**Comment by IgnisDa** [comment]
> I'd be okay with that, in which case it would be great if `setup.py` did not hard-code the same dependencies, but loaded them from `requirements.txt` and `requirements-dev.txt` and/or `requirements-test.txt`.
> 
> Thanks!

Even though that can be done, it's not recommended. See https://stackoverflow.com/a/16624700/11667450

**Comment by IgnisDa** [comment]
Closing this because the master branch has a lot of merge conflicts #42

**Pull request closed without merging**
